"""
protocols.py: 
    Part of the example dicom2sphn package.
    It contains the protocols for the application.
"""
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class LoggerProtocol(Protocol):
    """Protocol for the logger to ensure it has the necessary methods."""
    def debug(self, msg: str, *args, **kwargs) -> None: ...
    def info(self, msg: str, *args, **kwargs) -> None: ...
    def warning(self, msg: str, *args, **kwargs) -> None: ...
    def error(self, msg: str, *args, **kwargs) -> None: ...
    def critical(self, msg: str, *args, **kwargs) -> None: ...

@runtime_checkable
class DBProtocol(Protocol):
    """Protocol for the database connection to ensure it has the necessary methods."""
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def execute_query(self, query: str) -> Any: ...

